name: NPM

concurrency:
    group: NPM-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    security-events: write
    contents: write
    pull-requests: write

on:
    workflow_dispatch:
    release:
        types: [created]
    workflow_call:

jobs:
    Publish:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            id-token: write

        steps:
            - uses: actions/checkout@v4.1.7

            - uses: actions/setup-node@v4.0.2
              with:
                  node-version: "18"
                  registry-url: "https://registry.npmjs.org"

            - run: npm install -g npm

            - name: Publish ./wasm-component-model-async
              continue-on-error: true
              working-directory: ./wasm-component-model-async
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./wasm-component-model-resource
              continue-on-error: true
              working-directory: ./wasm-component-model-resource
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./wasm-component-model
              continue-on-error: true
              working-directory: ./wasm-component-model
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./wasm-language-server
              continue-on-error: true
              working-directory: ./wasm-language-server
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./wasm-language-server/server
              continue-on-error: true
              working-directory: ./wasm-language-server/server
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
